name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.0.x'
        
    - name: Publish .NET Project
      run: dotnet publish GameScoreboard.csproj -c Release -o release --nologo
    
    - name: List release directory
      run: ls -la release
      
    - name: Find wwwroot and copy to root folder
      run: |
        # Find the wwwroot directory
        WWWROOT_PATH=$(find release -type d -name "wwwroot" | head -n 1)
        if [ -z "$WWWROOT_PATH" ]; then
          echo "wwwroot directory not found!"
          exit 1
        fi
        echo "Found wwwroot at $WWWROOT_PATH"
        
        # Find the _framework directory
        FRAMEWORK_PATH=$(find release -type d -name "_framework" | head -n 1)
        if [ -z "$FRAMEWORK_PATH" ]; then
          echo "_framework directory not found!"
          exit 1
        fi
        echo "Found _framework at $FRAMEWORK_PATH"
        
        # Ensure the destination wwwroot directory exists
        mkdir -p release/deploy
        
        # Copy all content from found wwwroot to deployment directory
        cp -r $WWWROOT_PATH/* release/deploy/
        
        # Copy framework files if they're not already in the wwwroot
        if [ ! -d "release/deploy/_framework" ]; then
          mkdir -p release/deploy/_framework
          cp -r $FRAMEWORK_PATH/* release/deploy/_framework/
        fi
        
        # Look for the index.html file
        INDEX_HTML=$(find release -name "index.html" | head -n 1)
        if [ -z "$INDEX_HTML" ]; then
          echo "index.html not found!"
          exit 1
        fi
        echo "Found index.html at $INDEX_HTML"
        cp $INDEX_HTML release/deploy/
        
        # List the final deployment directory
        echo "Final deployment directory contents:"
        ls -la release/deploy
    
    # Update the base href in index.html
    - name: Update base href
      run: |
        sed -i 's|<base href=.*/>|<base href="/TeamArena/" />|' release/deploy/index.html
        grep "<base" release/deploy/index.html
        
    # Copy index.html to 404.html for SPA routing
    - name: Copy index.html to 404.html
      run: cp release/deploy/index.html release/deploy/404.html
      
    # Add .nojekyll file to tell GitHub pages not to use Jekyll processing
    - name: Add .nojekyll file
      run: touch release/deploy/.nojekyll
      
    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: release/deploy 